name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-integration:
    runs-on: "ubuntu-${{ matrix.ubuntu }}"
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - ubuntu: 20.04
            containerd: v1.7.16
    env:
      UBUNTU_VERSION: "${{ matrix.ubuntu }}"
      CONTAINERD_VERSION: "${{ matrix.containerd }}"
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path:
            ~/registry-proxy-cache
            /var/lib/docker/buildkit
          key: always
          # save-always: true
      - name: "Configure and start proxy cache"
        run: |
          # ${{ env.UBUNTU_VERSION }}-${{ env.CONTAINERD_VERSION }}
          mkdir -p ~/registry-proxy-cache
          sudo mkdir -p /var/lib/docker/buildkit
          echo "===== Testing ===="
          ls -lA ~/registry-proxy-cache
          echo "===== Was there some cache already? SHOULD BE ^ ===="
          echo "===== Testing ===="
          echo bla >> ~/registry-proxy-cache/fooofooo
          echo "===== Testing ===="
          ls -lA ~/registry-proxy-cache
          echo "===== Testing ===="
          echo "${{ env.UBUNTU_VERSION }}-${{ env.CONTAINERD_VERSION }}"
          echo "done"
